#!/bin/bash

# adjust the variables section below
#
# then: place this in /etc/init.d
# then: chmod +x /etc/init.d/sonos-monitor
# then: update-rc.d sonos-monitor defaults
#
# start daemon with /etc/init.d/sonos-monitor start
# stop it with /etc/init.d/sonos-monitor stop

DAEMON=/usr/bin/python
ARGS=home/pi/sonos/sonos-monitor.py
LOG=/home/pi/sonos/sonos-monitor.log
PIDFILE=/var/run/sonos-monitor.pid
USER=pi
GROUP=pi

case "$1" in
  start)
    echo "Starting server"
    /sbin/start-stop-daemon --start --pidfile $PIDFILE \
        --user $USER --group $GROUP \
        -b --make-pidfile \
        --chuid $USER \
        --startas /bin/bash -- -c "exec $DAEMON $ARGS >>$LOG 2>&1"
    ;;
  stop)
    echo "Stopping server"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --verbose
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac

exit 0
